<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_css-textinput-11aywtz r-placeho_f2d72d</name>
   <tag></tag>
   <elementGuidId>a79c604f-fbcb-4f7a-8fb3-4a53f1a2d1c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.css-textinput-11aywtz.r-placeholderTextColor-6taxm2.r-borderBottomColor-170gynj.r-borderBottomWidth-qklmqi.r-color-13gxpnn.r-height-eu3ka.r-marginBottom-1ifxtd0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='teste2@gmail.com']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abbd4e5c-2076-41ae-ae6e-cc4c93574d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>23cf7286-e3f7-423c-9bdf-c3dde939da7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>61b8986c-a013-49b9-b4c8-0f79a3b9d263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>494ff4a3-9c47-425e-b674-103d818e2120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>efef2dd7-8029-4745-a83a-0dcf5cfba301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>4dba4f70-0a75-4ffc-94bf-68e91cc3da3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a4afadd8-74c9-4213-864a-08f87ce488c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d0b6ccf-ebb5-44ca-a9e5-455167e17758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>virtualkeyboardpolicy</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>bc36c0e5-c5e7-42a7-b7f8-c27fd062423b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-textinput-11aywtz r-placeholderTextColor-6taxm2 r-borderBottomColor-170gynj r-borderBottomWidth-qklmqi r-color-13gxpnn r-height-eu3ka r-marginBottom-1ifxtd0</value>
      <webElementGuid>4bc25aaa-f5cb-4cc1-a8dd-712178af87ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5e5dccdf-0787-49ca-8213-75d25f392944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>teste2@gmail.com</value>
      <webElementGuid>02ee2f51-98ad-4691-8a2e-b1b786c06b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wfd-id</name>
      <type>Main</type>
      <value>id0</value>
      <webElementGuid>c3fccb27-a8e8-4660-9e26-d14672477098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-view-g5y9jx r-flex-13awgt0&quot;]/div[@class=&quot;css-view-g5y9jx r-flex-13awgt0 r-bottom-1p0dtai r-left-1d2f490 r-position-u8s1d r-right-zchlnj r-top-ipm5af&quot;]/div[@class=&quot;css-view-g5y9jx r-flex-13awgt0&quot;]/div[@class=&quot;css-view-g5y9jx r-flex-13awgt0&quot;]/div[@class=&quot;css-view-g5y9jx r-backgroundColor-4dcnlu r-flex-13awgt0 r-justifyContent-1777fci r-padding-d23pfw&quot;]/input[@class=&quot;css-textinput-11aywtz r-placeholderTextColor-6taxm2 r-borderBottomColor-170gynj r-borderBottomWidth-qklmqi r-color-13gxpnn r-height-eu3ka r-marginBottom-1ifxtd0&quot;]</value>
      <webElementGuid>d4e3a150-d817-4b70-addc-96944387e5da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='teste2@gmail.com']</value>
      <webElementGuid>f8e0eb76-86b6-44aa-a030-00746d4738e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/input</value>
      <webElementGuid>d491efaf-b96f-41c9-b08c-5c6cad4c861f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f312f7bc-dea9-4315-958a-5d6ac225e21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email' and @type = 'email']</value>
      <webElementGuid>e0365358-44ea-4e21-984a-bfbd2e3b2a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='T']</value>
      <webElementGuid>9d0cbf5c-d92a-4fd5-9269-32692ab2277f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/input[2]</value>
      <webElementGuid>eadaf1ab-74e5-4d10-b840-e2fef4e48d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>abaccda4-f730-41a1-8a85-394ddc68009f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Senha' and @type = 'password']</value>
      <webElementGuid>c70d4823-2468-44d3-a783-6c9ed2e885e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='t']</value>
      <webElementGuid>be3ee126-38bc-4055-8e6c-4fccac9582ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
