<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Editar Perfil_css-textinput-11aywtz r_9c9e5f_11</name>
   <tag></tag>
   <elementGuidId>cf683fe2-19df-4d19-b8cf-48c3217fd64e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='111111111111']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Telefone&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de674038-ccf2-40a9-a836-52becf486a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Telefone</value>
      <webElementGuid>57f09a30-cabc-4571-8c02-aa2c5b9a8627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
      <webElementGuid>0beb65a7-2448-4e9c-8c8d-2922fc5b35b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e6ae9bd1-c2cc-4c4a-a088-a4890afaf77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>be9c7876-16cb-4799-910d-3ce35b29193d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>766def92-a5ec-4926-a7d5-8ab139e7bfd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>12faa980-124e-40ba-b843-c0c73e536ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e9e85f01-eef9-4a95-871e-076dff9779b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>virtualkeyboardpolicy</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>9ae3c80c-8933-4256-a1d7-e6d5ceef2f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-textinput-11aywtz r-placeholderTextColor-6taxm2 r-backgroundColor-spuqty r-borderColor-f5trrm r-borderRadius-1dzdj1l r-borderWidth-rs99b7 r-boxShadow-19x73d9 r-color-1ytmlu4 r-fontSize-1i10wst r-padding-nsbfu8</value>
      <webElementGuid>3d40ab66-f644-4854-8b6b-3ed8a1383048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>c5cf95f2-8e61-4c6e-bf63-bf4911f8b092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>111111111111</value>
      <webElementGuid>ca1326c3-aa6b-4d66-a4d0-aa0cf444307e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;css-view-g5y9jx r-flex-13awgt0&quot;]/div[@class=&quot;css-view-g5y9jx r-flex-13awgt0 r-bottom-1p0dtai r-left-1d2f490 r-position-u8s1d r-right-zchlnj r-top-ipm5af&quot;]/div[@class=&quot;css-view-g5y9jx r-flex-13awgt0&quot;]/div[@class=&quot;css-view-g5y9jx r-flex-13awgt0&quot;]/div[@class=&quot;css-view-g5y9jx r-backgroundColor-4dcnlu r-flex-13awgt0 r-justifyContent-1777fci r-padding-d23pfw&quot;]/div[@class=&quot;css-view-g5y9jx r-backgroundColor-spuqty r-borderRadius-1dzdj1l r-boxShadow-kixfm4 r-marginBottom-1ifxtd0&quot;]/input[@class=&quot;css-textinput-11aywtz r-placeholderTextColor-6taxm2 r-backgroundColor-spuqty r-borderColor-f5trrm r-borderRadius-1dzdj1l r-borderWidth-rs99b7 r-boxShadow-19x73d9 r-color-1ytmlu4 r-fontSize-1i10wst r-padding-nsbfu8&quot;]</value>
      <webElementGuid>d287dd86-1f1b-4f7d-bf70-617cc3f40fb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='111111111111']</value>
      <webElementGuid>8e087328-a23e-4cba-bae0-28daedb87c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div/div/div[7]/input</value>
      <webElementGuid>1694ab23-3331-46d5-a2e9-d56bdc5a4510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>dbd6feea-3530-4e5b-b59e-56129531878b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Telefone' and @type = 'tel']</value>
      <webElementGuid>7789f7fe-1aca-4e0f-b1a2-6905ad382353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='551197568962']</value>
      <webElementGuid>239dd28d-3caf-4e34-9138-15598280df8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
